import { createReducer } from 'redux-act';
import {
    posprinter_savetemplate,
} from '../actions/index.js';
// import moment from 'moment';

const initial = {
    posprinter: {
        billnodes:{
            contactname:{
                fontSize: 14,
                id: "contactname",
                rotation: 0,
                text: "联系人",
                x: 20,
                y: 180,
                fieldname:'contactname',
                type:'text',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'联系人:',
                isprintlabel:true,
            },
            contacttel:{
                fontSize: 14,
                id: "contacttel",
                rotation: 0,
                text: "联系电话",
                x: 20,
                y: 200,
                fieldname:'contacttel',
                type:'text',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'联系电话:',
                isprintlabel:true,
            },
            count:{
                fontSize: 14,
                id: "count",
                rotation: 0,
                text: "数量",
                type: 'text',
                fixedwidth:8,
                x: 140,
                y: 280,
                fieldname:'count',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:1,
                label:'数量:',
                isprintlabel:false,
            },
            deliveraddress:{
                fontSize: 14,
                id: "deliveraddress",
                rotation: 0,
                text: "送餐地址",
                type: 'text',
                x: 20,
                y: 240,
                fieldname:'deliveraddress',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'送餐地址:',
                isprintlabel:true,
            },
            delivertime:{
                fontSize: 14,
                id: "delivertime",
                rotation: 0,
                text: "送餐时间",
                type: 'text',
                x: 20,
                y: 140,
                fieldname:'delivertime',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'送餐时间:',
                isprintlabel:true,
            },
            discount:{
                fontSize: 14,
                id: "discount",
                rotation: 0,
                text: "优惠金额",
                type: 'text',
                x: 20,
                y: 380,
                fieldname:'discount',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:1,
                label:'优惠金额:',
                isprintlabel:true,
            },
            products:{
                fontSize: 14,
                id: "products",
                rotation: 0,
                text: "商品",
                type:'table',
                align:'LT',
                fieldname:'products',
                lines:[['name','count','price']],
                x: 20,
                y: 280,
                label:'商品:',
                isprintlabel:false,
            },
            name:{
                fontSize: 14,
                id: "name",
                rotation: 0,
                text: "商品名",
                type: 'text',
                x: 70,
                y: 280,
                fieldname:'name',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'商品名:',
                isprintlabel:false,
            },
            orderno:{
                fontSize: 14,
                id: "orderno",
                rotation: 0,
                text: "订单号",
                type: 'text',
                x: 20,
                y: 100,
                fieldname:'orderno',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'订单号:',
                isprintlabel:true,
            },
            ordersrc:{
                fontSize: 14,
                id: "ordersrc",
                rotation: 0,
                text: "订单来源",
                type: 'text',
                x: 20,
                y: 60,
                fieldname:'ordersrc',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'订单来源:',
                isprintlabel:true,
            },
            ordertime:{
                fontSize: 14,
                id: "ordertime",
                rotation: 0,
                text: "下单时间",
                type: 'text',
                x: 20,
                y: 120,
                fieldname:'ordertime',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'下单时间:',
                isprintlabel:true,
            },
            packetprice:{
                fontSize: 14,
                id: "packetprice",
                rotation: 0,
                text: "打包盒",
                type: 'text',
                x: 20,
                y: 340,
                fieldname:'packetprice',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:1,
                label:'打包盒:',
                isprintlabel:true,
            },
            payprice:{
                fontSize: 14,
                id: "payprice",
                rotation: 0,
                text: "支付金额",
                type: 'text',
                x: 20,
                y: 400,
                fieldname:'payprice',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'支付金额:',
                isprintlabel:true,
            },
            paytype:{
                fontSize: 14,
                id: "paytype",
                rotation: 0,
                text: "支付类型",
                type: 'text',
                x: 20,
                y: 220,
                fieldname:'paytype',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'支付类型:',
                isprintlabel:true,
            },
            price:{
                fontSize: 14,
                id: "price",
                rotation: 0,
                text: "价格",
                type: 'text',
                x: 200,
                y: 280,
                fieldname:'price',
                fixedwidth:4,
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'价格:',
                isprintlabel:false,
            },
            shopname:{
                fontSize: 14,
                id: "shopname",
                rotation: 0,
                text: "店铺名",
                type: 'text',
                x: 180,
                y: 20,
                fieldname:'shopname',
                flag:'text',
                align:'CT',
                font:'B',
                fontwidth:2,
                fontheight:3,
                label:'店铺名:',
                isprintlabel:false,
            },
            shopno:{
                fontSize: 14,
                id: "shopno",
                rotation: 0,
                text: "商户流水号",
                type: 'text',
                x: 20,
                y: 80,
                fieldname:'shopno',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:2,
                label:'商户流水号:',
                isprintlabel:true,
            },
            total:{
                fontSize: 14,
                id: "total",
                rotation: 0,
                text: "总计",
                type: 'text',
                x: 20,
                y: 360,
                fieldname:'total',
                flag:'text',
                align:'LT',
                font:'A',
                fontwidth:1,
                fontheight:1,
                label:'总计:',
                isprintlabel:true,
            }
        },
        //   '二维码': { 
        //       id: "二维码", 
        //       data: "M1 1h7v7h-7zM9 1h2v2h-1v-1h-1zM13 1h1v3h-1zM15 1h7v7h-7zM2 2v5h5v-5zM16 2v5h5v-5zM3 3h3v3h-3zM9 3h1v2h2v1h-3zM11 3h1v1h-1zM17 3h3v3h-3zM12 4h1v1h-1zM9 7h1v1h-1zM11 7h1v3h-1v-1h-1v-1h1zM13 7h1v1h-1zM1 9h4v1h2v1h1v1h-1v1h1v1h-2v-1h-1v1h-2v-3h1v1h2v-1h-2v-1h-1v1h-2zM7 9h1v1h-1zM9 9h1v3h-1zM14 9h1v1h-1zM17 9h3v2h-2v1h-1v-1h-1v4h-1v-2h-2v-3h1v2h1v-2h2zM21 9h1v2h-1zM11 11h1v1h-1zM10 12h1v1h-1zM19 12h1v1h-1zM21 12h1v1h-1zM11 13h2v2h-1v-1h-1zM20 13h1v1h-1zM9 14h2v3h-1v-2h-1zM17 14h3v1h-3zM1 15h7v7h-7zM16 15h1v1h2v1h2v2h-1v-1h-1v1h-1v-1h-2v-1h-2v-1h2zM21 15h1v1h-1zM2 16v5h5v-5zM12 16h1v1h-1zM3 17h3v3h-3zM11 17h1v1h1v-1h1v2h-3zM9 18h1v4h-1zM15 19h3v1h-1v2h-1v-2h-1zM18 20h2v1h-2zM21 20h1v1h-1zM11 21h3v1h-3z",
        //       type: "Path", 
        //       fill: "black",
        //       rotation: 0,
        //       x: 200, 
        //       y: 140,
        //       scale: {x: 4, y: 4} 
        // },
        //   '会员价': {
        //       fontSize: 12,
        //       id: "会员价",
        //       text: "会员价",
        //       type: "Text",
        //       rotation: 0,
        //       x: 125,
        //       y: 120
        //   },
        //   '单位': {
        //       fontSize: 12,
        //       id: "单位",
        //       text: "单位",
        //       type: "Text",
        //       rotation: 0,
        //       x: 180,
        //       y: 20,
        //   },
        //   '原价': {
        //       fontSize: 12,
        //       id: "原价",
        //       text: "原价",
        //       type: "Text",
        //       rotation: 0,
        //       x: 0,
        //       y: 120,
        //   },
        //   '品名': {
        //       fontSize: 12,
        //       id: "品名",
        //       text: "品名",
        //       type: "Text",
        //       rotation: 0,
        //       x: 0,
        //       y: 80,
        //   },
        //   '折扣价': {
        //       fontSize: 12,
        //       id: "折扣价",
        //       text: "折扣价",
        //       type: "Text",
        //       rotation: 0,
        //       x: 250,
        //       y: 120,
        //   },
        //   '数量': {
        //       fontSize: 12,
        //       id: "数量",
        //       text: "数量",
        //       type: "Text",
        //       rotation: 0,
        //       x: 375,
        //       y: 120,
        //   },
        //   '日期': {
        //       fontSize: 12,
        //       id: "日期",
        //       text: "日期",
        //       type: "Text",
        //       rotation: 0,
        //       x: 400,
        //       y: 80,
        //   },
        // },
        billdata:{
          '单位': '武进万达',
          '品名': '麻辣烫',
          productdetail:[
              {
                  '原价': 20,
                  '会员价': 18,
                  '折扣价': 15,
                  '数量': 2,
              },
              {
                  '原价': 30,
                  '会员价': 28,
                  '折扣价': 25,
                  '数量': 1,
              },
          ],
          '二维码': '二维码',
        },
        tagnodes: {
            二维码:{
                data: "M1 1h7v7h-7zM9 1h2v2h-1v-1h-1zM13 1h1v3h-1zM15 1h7v7h-7zM2 2v5h5v-5zM16 2v5h5v-5zM3 3h3v3h-3zM9 3h1v2h2v1h-3zM11 3h1v1h-1zM17 3h3v3h-3zM12 4h1v1h-1zM9 7h1v1h-1zM11 7h1v3h-1v-1h-1v-1h1zM13 7h1v1h-1zM1 9h4v1h2v1h1v1h-1v1h1v1h-2v-1h-1v1h-2v-3h1v1h2v-1h-2v-1h-1v1h-2zM7 9h1v1h-1zM9 9h1v3h-1zM14 9h1v1h-1zM17 9h3v2h-2v1h-1v-1h-1v4h-1v-2h-2v-3h1v2h1v-2h2zM21 9h1v2h-1zM11 11h1v1h-1zM10 12h1v1h-1zM19 12h1v1h-1zM21 12h1v1h-1zM11 13h2v2h-1v-1h-1zM20 13h1v1h-1zM9 14h2v3h-1v-2h-1zM17 14h3v1h-3zM1 15h7v7h-7zM16 15h1v1h2v1h2v2h-1v-1h-1v1h-1v-1h-2v-1h-2v-1h2zM21 15h1v1h-1zM2 16v5h5v-5zM12 16h1v1h-1zM3 17h3v3h-3zM11 17h1v1h1v-1h1v2h-3zM9 18h1v4h-1zM15 19h3v1h-1v2h-1v-2h-1zM18 20h2v1h-2zM21 20h1v1h-1zM11 21h3v1h-3z",
                fill: "black",
                id: "二维码",
                type: "Path",
                rotation: 0,
                scale: {x: 4, y: 4},
                x: 160,
                y: 60,
            },
            原价:{
                fontSize: 18,
                id: "原价",
                type: "Text",
                rotation: 0,
                text: "价格",
                x: 190,
                y: 160,
            },
            品名:{
                fontSize: 22,
                id: "品名",
                type: "Text",
                rotation: 0,
                text: "品名",
                x: 190,
                y: 40,
            }
        },
        tagdata: {
            '店名': '武进万达',
            '品名': '麻辣烫',
            '原价': 20,
            '会员价': 18,
            '折扣价': 15,
            '数量': 2,
            '二维码': '二维码',
          },
    },

};

const posprinter = createReducer({
    [posprinter_savetemplate]: (state, payload) => {
        const {groupnodes} = payload;
        return { ...state, groupnodes:{...groupnodes}};
    },
}, initial.posprinter);

export default posprinter;
